# Generated by Django 2.2.10 on 2020-08-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tegs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=256, verbose_name='Название')),
                ('scopes', models.ManyToManyField(related_name='scopes', to='articles.Article')),
            ],
        ),
    ]
