# Generated by Django 2.2.10 on 2020-08-25 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Статьи', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='main_teg',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='tegs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Теги', to='articles.Tegs'),
        ),
    ]
