# Generated by Django 2.2.10 on 2020-08-26 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200825_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='tegs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Tegs'),
        ),
    ]
