# Generated by Django 2.2.10 on 2020-08-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200826_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['main_teg']},
        ),
    ]
