# Generated by Django 2.2.10 on 2020-08-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200827_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['-main_teg']},
        ),
    ]
